---
swagger: "2.0"
info:
  description: "This is a the API for Getting Operators per City, Area or Coordinate"
  version: "1.0.0"
  title: "Operator-api"
  contact:
    name: "info@codefor.nl"
  license:
    name: "GPL-3.0"
    url: "https://raw.githubusercontent.com/codefornl/operator-api/master/LICENSE"
basePath: "/api"
schemes:
#- "https"
- "http"
paths:
  /upload:
    post:
      tags:
        - "upload"
      summary: "Upload a file"
      description: ""
      operationId: "postupload"
      consumes:
        - "multipart/form-data"
        - "application/x-www-form-urlencoded"
      parameters:
        - name: "file"
          in: "formData"
          description: "GeoJSON file to create table from. Will be validated during upload"
          required: true
          type: "file"
        - name: "table" 
          in: "formData"
          type: "string"
          description: "If not set, generates table name"
        - name: "level"
          in: "formData"
          type: "number"
          format: "int64"
          description: "Integer. The higher the integer, the closer to the ground. Can be used to set a hierarchy. If not set, will be set to 1 (highest hierarchy. Can later be edited"
        - name: "name_column"
          in: "formData"
          type: "string"
          required: true
          description: "The name that can be used for display and to search on"
        - name: "id_column"
          in: "formData"
          type: "string"
          description: "The name of the column in the source file that holds unique identifiers. Will use autogenerated when not set"
        - name: "action"
          in: "formData"
          type: "string"
          default: "append"
          description: "can be append or replace, should the table exist."
          enum: 
          - append
          - replace
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Upload"

  /jurisdiction:
    get:
      tags:
      - "jurisdiction"
      summary: "Get jurisdiction for a given area"
      description: ""
      operationId: "getjurisdiction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "q"
        description: "Search query"
        required: false
        type: "string"
      - in: "query"
        name: "lat"
        description: "Latitude"
        required: false
        type: "number"
        format: "float"
      - in: "query"
        name: "lon"
        description: "Longitude"
        required: false
        type: "number"
        format: "float"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Jurisdiction"