---
swagger: "2.0"
info:
  description: "This is a the API for Getting Operators per City, Area or Coordinate"
  version: "1.0.0"
  title: "Operator-api"
  contact:
    name: "info@codefor.nl"
  license:
    name: "GPL-3.0"
    url: "https://raw.githubusercontent.com/codefornl/operator-api/master/LICENSE"
basePath: "/api"
schemes:
#- "https"
- "http"
paths:
  /jurisdiction:
    get:
      tags:
      - "jurisdiction"
      summary: "Get jurisdiction for a given area"
      description: ""
      operationId: "getjurisdiction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "q"
        description: "Search query"
        required: false
        type: "string"
      - in: "query"
        name: "lat"
        description: "Latitude"
        required: false
        type: "number"
        format: "float"
      - in: "query"
        name: "lon"
        description: "Longitude"
        required: false
        type: "number"
        format: "float"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Jurisdiction"
